### ISSUE TITLE
Can't resolve "stream.smarkets.com"

### ISSUE THREAD

**Issue by Vitamin-B** [smarkets/smk_python_sdk#17]
Hi, I try to run the intro script and can't resolve host "stream.smarkets.com"
I also cant resolve it using google DNS server. On older "api.smarkets.com" I get timeout error.
```
>>> client.login()
INFO:smarkets.session.socket:connecting with new socket to stream.smarkets.com:3801
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda2/lib/python2.7/site-packages/smarkets/streaming_api/client.py", line 54, in login
    self.session.connect()
  File "/opt/anaconda2/lib/python2.7/site-packages/smarkets/streaming_api/session.py", line 90, in connect
    if self.socket.connect():
  File "/opt/anaconda2/lib/python2.7/site-packages/smarkets/streaming_api/session.py", line 253, in connect
    reraise(ConnectionError(self._error_message(exc)))
  File "/opt/anaconda2/lib/python2.7/site-packages/smarkets/errors.py", line 13, in reraise
    _six.reraise(type(exception), exception, tb)
  File "/opt/anaconda2/lib/python2.7/site-packages/smarkets/streaming_api/session.py", line 249, in connect
    sock.connect((self.settings.host, self.settings.port))
  File "/opt/anaconda2/lib/python2.7/ssl.py", line 876, in connect
    self._real_connect(addr, False)
  File "/opt/anaconda2/lib/python2.7/ssl.py", line 863, in _real_connect
    socket.connect(self, addr)
  File "/opt/anaconda2/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
smarkets.streaming_api.exceptions.ConnectionError: Error -2 connecting stream.smarkets.com:3801. Name or service not known.
>>> 
```

**Comment by Cally99** [comment]
I don't think this package is being maintained anymore. I'm following documentation and get same error.
